on:
  schedule:
  - cron: '35 10 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@stable
      env:
        GITH_EMAIL: derekzhou2015@email.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
